-- \set customer_gender_limit 100

-- Map surnames
CREATE TEMP TABLE surname_temp
(
	id		serial,
	surname	varchar(255)		
);

-- List from http://surnames.behindthename.com/top/lists/500ens1991.php
INSERT INTO surname_temp (surname) VALUES ('Smith');
INSERT INTO surname_temp (surname) VALUES ('Jones');
INSERT INTO surname_temp (surname) VALUES ('Williams');
INSERT INTO surname_temp (surname) VALUES ('Taylor');
INSERT INTO surname_temp (surname) VALUES ('Brown');
INSERT INTO surname_temp (surname) VALUES ('Davies');
INSERT INTO surname_temp (surname) VALUES ('Evans');
INSERT INTO surname_temp (surname) VALUES ('Wilson');
INSERT INTO surname_temp (surname) VALUES ('Thomas');
INSERT INTO surname_temp (surname) VALUES ('Johnson');
INSERT INTO surname_temp (surname) VALUES ('Roberts');
INSERT INTO surname_temp (surname) VALUES ('Robinson');
INSERT INTO surname_temp (surname) VALUES ('Thompson');
INSERT INTO surname_temp (surname) VALUES ('Wright');
INSERT INTO surname_temp (surname) VALUES ('Walker');
INSERT INTO surname_temp (surname) VALUES ('White');
INSERT INTO surname_temp (surname) VALUES ('Edwards');
INSERT INTO surname_temp (surname) VALUES ('Hughes');
INSERT INTO surname_temp (surname) VALUES ('Green');
INSERT INTO surname_temp (surname) VALUES ('Hall');
INSERT INTO surname_temp (surname) VALUES ('Lewis');
INSERT INTO surname_temp (surname) VALUES ('Harris');
INSERT INTO surname_temp (surname) VALUES ('Clarke');
INSERT INTO surname_temp (surname) VALUES ('Patel');
INSERT INTO surname_temp (surname) VALUES ('Jackson');
INSERT INTO surname_temp (surname) VALUES ('Wood');
INSERT INTO surname_temp (surname) VALUES ('Turner');
INSERT INTO surname_temp (surname) VALUES ('Martin');
INSERT INTO surname_temp (surname) VALUES ('Cooper');
INSERT INTO surname_temp (surname) VALUES ('Hill');
INSERT INTO surname_temp (surname) VALUES ('Ward');
INSERT INTO surname_temp (surname) VALUES ('Morris');
INSERT INTO surname_temp (surname) VALUES ('Moore');
INSERT INTO surname_temp (surname) VALUES ('Clark');
INSERT INTO surname_temp (surname) VALUES ('Lee');
INSERT INTO surname_temp (surname) VALUES ('King');
INSERT INTO surname_temp (surname) VALUES ('Baker');
INSERT INTO surname_temp (surname) VALUES ('Harrison');
INSERT INTO surname_temp (surname) VALUES ('Morgan');
INSERT INTO surname_temp (surname) VALUES ('Allen');
INSERT INTO surname_temp (surname) VALUES ('James');
INSERT INTO surname_temp (surname) VALUES ('Scott');
INSERT INTO surname_temp (surname) VALUES ('Phillips');
INSERT INTO surname_temp (surname) VALUES ('Watson');
INSERT INTO surname_temp (surname) VALUES ('Davis');
INSERT INTO surname_temp (surname) VALUES ('Parker');
INSERT INTO surname_temp (surname) VALUES ('Price');
INSERT INTO surname_temp (surname) VALUES ('Bennett');
INSERT INTO surname_temp (surname) VALUES ('Young');
INSERT INTO surname_temp (surname) VALUES ('Griffiths');
INSERT INTO surname_temp (surname) VALUES ('Mitchell');
INSERT INTO surname_temp (surname) VALUES ('Kelly');
INSERT INTO surname_temp (surname) VALUES ('Cook');
INSERT INTO surname_temp (surname) VALUES ('Carter');
INSERT INTO surname_temp (surname) VALUES ('Richardson');
INSERT INTO surname_temp (surname) VALUES ('Bailey');
INSERT INTO surname_temp (surname) VALUES ('Collins');
INSERT INTO surname_temp (surname) VALUES ('Bell');
INSERT INTO surname_temp (surname) VALUES ('Shaw');
INSERT INTO surname_temp (surname) VALUES ('Murphy');
INSERT INTO surname_temp (surname) VALUES ('Miller');
INSERT INTO surname_temp (surname) VALUES ('Cox');
INSERT INTO surname_temp (surname) VALUES ('Richards');
INSERT INTO surname_temp (surname) VALUES ('Khan');
INSERT INTO surname_temp (surname) VALUES ('Marshall');
INSERT INTO surname_temp (surname) VALUES ('Anderson');
INSERT INTO surname_temp (surname) VALUES ('Simpson');
INSERT INTO surname_temp (surname) VALUES ('Ellis');
INSERT INTO surname_temp (surname) VALUES ('Adams');
INSERT INTO surname_temp (surname) VALUES ('Singh');
INSERT INTO surname_temp (surname) VALUES ('Begum');
INSERT INTO surname_temp (surname) VALUES ('Wilkinson');
INSERT INTO surname_temp (surname) VALUES ('Foster');
INSERT INTO surname_temp (surname) VALUES ('Chapman');
INSERT INTO surname_temp (surname) VALUES ('Powell');
INSERT INTO surname_temp (surname) VALUES ('Webb');
INSERT INTO surname_temp (surname) VALUES ('Rogers');
INSERT INTO surname_temp (surname) VALUES ('Gray');
INSERT INTO surname_temp (surname) VALUES ('Mason');
INSERT INTO surname_temp (surname) VALUES ('Ali');
INSERT INTO surname_temp (surname) VALUES ('Hunt');
INSERT INTO surname_temp (surname) VALUES ('Hussain');
INSERT INTO surname_temp (surname) VALUES ('Campbell');
INSERT INTO surname_temp (surname) VALUES ('Matthews');
INSERT INTO surname_temp (surname) VALUES ('Owen');
INSERT INTO surname_temp (surname) VALUES ('Palmer');
INSERT INTO surname_temp (surname) VALUES ('Holmes');
INSERT INTO surname_temp (surname) VALUES ('Mills');
INSERT INTO surname_temp (surname) VALUES ('Barnes');
INSERT INTO surname_temp (surname) VALUES ('Knight');
INSERT INTO surname_temp (surname) VALUES ('Lloyd');
INSERT INTO surname_temp (surname) VALUES ('Butler');
INSERT INTO surname_temp (surname) VALUES ('Russell');
INSERT INTO surname_temp (surname) VALUES ('Barker');
INSERT INTO surname_temp (surname) VALUES ('Fisher');
INSERT INTO surname_temp (surname) VALUES ('Stevens');
INSERT INTO surname_temp (surname) VALUES ('Jenkins');
INSERT INTO surname_temp (surname) VALUES ('Murray');
INSERT INTO surname_temp (surname) VALUES ('Dixon');
INSERT INTO surname_temp (surname) VALUES ('Harvey');
INSERT INTO surname_temp (surname) VALUES ('Graham');
INSERT INTO surname_temp (surname) VALUES ('Pearson');
INSERT INTO surname_temp (surname) VALUES ('Ahmed');
INSERT INTO surname_temp (surname) VALUES ('Fletcher');
INSERT INTO surname_temp (surname) VALUES ('Walsh');
INSERT INTO surname_temp (surname) VALUES ('Kaur');
INSERT INTO surname_temp (surname) VALUES ('Gibson');
INSERT INTO surname_temp (surname) VALUES ('Howard');
INSERT INTO surname_temp (surname) VALUES ('Andrews');
INSERT INTO surname_temp (surname) VALUES ('Stewart');
INSERT INTO surname_temp (surname) VALUES ('Elliott');
INSERT INTO surname_temp (surname) VALUES ('Reynolds');
INSERT INTO surname_temp (surname) VALUES ('Saunders');
INSERT INTO surname_temp (surname) VALUES ('Payne');
INSERT INTO surname_temp (surname) VALUES ('Fox');
INSERT INTO surname_temp (surname) VALUES ('Ford');
INSERT INTO surname_temp (surname) VALUES ('Pearce');
INSERT INTO surname_temp (surname) VALUES ('Day');
INSERT INTO surname_temp (surname) VALUES ('Brooks');
INSERT INTO surname_temp (surname) VALUES ('West');
INSERT INTO surname_temp (surname) VALUES ('Lawrence');
INSERT INTO surname_temp (surname) VALUES ('Cole');
INSERT INTO surname_temp (surname) VALUES ('Atkinson');
INSERT INTO surname_temp (surname) VALUES ('Bradley');
INSERT INTO surname_temp (surname) VALUES ('Spencer');
INSERT INTO surname_temp (surname) VALUES ('Gill');
INSERT INTO surname_temp (surname) VALUES ('Dawson');
INSERT INTO surname_temp (surname) VALUES ('Ball');
INSERT INTO surname_temp (surname) VALUES ('Burton');
INSERT INTO surname_temp (surname) VALUES ('O''Brien');
INSERT INTO surname_temp (surname) VALUES ('Watts');
INSERT INTO surname_temp (surname) VALUES ('Rose');
INSERT INTO surname_temp (surname) VALUES ('Booth');
INSERT INTO surname_temp (surname) VALUES ('Perry');
INSERT INTO surname_temp (surname) VALUES ('Ryan');
INSERT INTO surname_temp (surname) VALUES ('Grant');
INSERT INTO surname_temp (surname) VALUES ('Wells');
INSERT INTO surname_temp (surname) VALUES ('Armstrong');
INSERT INTO surname_temp (surname) VALUES ('Francis');
INSERT INTO surname_temp (surname) VALUES ('Rees');
INSERT INTO surname_temp (surname) VALUES ('Hayes');
INSERT INTO surname_temp (surname) VALUES ('Hart');
INSERT INTO surname_temp (surname) VALUES ('Hudson');
INSERT INTO surname_temp (surname) VALUES ('Newman');
INSERT INTO surname_temp (surname) VALUES ('Barrett');
INSERT INTO surname_temp (surname) VALUES ('Webster');
INSERT INTO surname_temp (surname) VALUES ('Hunter');
INSERT INTO surname_temp (surname) VALUES ('Gregory');
INSERT INTO surname_temp (surname) VALUES ('Carr');
INSERT INTO surname_temp (surname) VALUES ('Lowe');
INSERT INTO surname_temp (surname) VALUES ('Page');
INSERT INTO surname_temp (surname) VALUES ('Marsh');
INSERT INTO surname_temp (surname) VALUES ('Riley');
INSERT INTO surname_temp (surname) VALUES ('Dunn');
INSERT INTO surname_temp (surname) VALUES ('Woods');
INSERT INTO surname_temp (surname) VALUES ('Parsons');
INSERT INTO surname_temp (surname) VALUES ('Berry');
INSERT INTO surname_temp (surname) VALUES ('Stone');
INSERT INTO surname_temp (surname) VALUES ('Reid');
INSERT INTO surname_temp (surname) VALUES ('Holland');
INSERT INTO surname_temp (surname) VALUES ('Hawkins');
INSERT INTO surname_temp (surname) VALUES ('Harding');
INSERT INTO surname_temp (surname) VALUES ('Porter');
INSERT INTO surname_temp (surname) VALUES ('Robertson');
INSERT INTO surname_temp (surname) VALUES ('Newton');
INSERT INTO surname_temp (surname) VALUES ('Oliver');
INSERT INTO surname_temp (surname) VALUES ('Reed');
INSERT INTO surname_temp (surname) VALUES ('Kennedy');
INSERT INTO surname_temp (surname) VALUES ('Williamson');
INSERT INTO surname_temp (surname) VALUES ('Bird');
INSERT INTO surname_temp (surname) VALUES ('Gardner');
INSERT INTO surname_temp (surname) VALUES ('Shah');
INSERT INTO surname_temp (surname) VALUES ('Dean');
INSERT INTO surname_temp (surname) VALUES ('Lane');
INSERT INTO surname_temp (surname) VALUES ('Cooke');
INSERT INTO surname_temp (surname) VALUES ('Bates');
INSERT INTO surname_temp (surname) VALUES ('Henderson');
INSERT INTO surname_temp (surname) VALUES ('Parry');
INSERT INTO surname_temp (surname) VALUES ('Burgess');
INSERT INTO surname_temp (surname) VALUES ('Bishop');
INSERT INTO surname_temp (surname) VALUES ('Walton');
INSERT INTO surname_temp (surname) VALUES ('Burns');
INSERT INTO surname_temp (surname) VALUES ('Nicholson');
INSERT INTO surname_temp (surname) VALUES ('Shepherd');
INSERT INTO surname_temp (surname) VALUES ('Ross');
INSERT INTO surname_temp (surname) VALUES ('Cross');
INSERT INTO surname_temp (surname) VALUES ('Long');
INSERT INTO surname_temp (surname) VALUES ('Freeman');
INSERT INTO surname_temp (surname) VALUES ('Warren');
INSERT INTO surname_temp (surname) VALUES ('Nicholls');
INSERT INTO surname_temp (surname) VALUES ('Hamilton');
INSERT INTO surname_temp (surname) VALUES ('Byrne');
INSERT INTO surname_temp (surname) VALUES ('Sutton');
INSERT INTO surname_temp (surname) VALUES ('McDonald');
INSERT INTO surname_temp (surname) VALUES ('Yates');
INSERT INTO surname_temp (surname) VALUES ('Hodgson');
INSERT INTO surname_temp (surname) VALUES ('Robson');
INSERT INTO surname_temp (surname) VALUES ('Curtis');
INSERT INTO surname_temp (surname) VALUES ('Hopkins');
INSERT INTO surname_temp (surname) VALUES ('O''Connor');
INSERT INTO surname_temp (surname) VALUES ('Harper');
INSERT INTO surname_temp (surname) VALUES ('Coleman');
INSERT INTO surname_temp (surname) VALUES ('Watkins');
INSERT INTO surname_temp (surname) VALUES ('Moss');
INSERT INTO surname_temp (surname) VALUES ('McCarthy');
INSERT INTO surname_temp (surname) VALUES ('Chambers');
INSERT INTO surname_temp (surname) VALUES ('O''Neill');
INSERT INTO surname_temp (surname) VALUES ('Griffin');
INSERT INTO surname_temp (surname) VALUES ('Sharp');
INSERT INTO surname_temp (surname) VALUES ('Hardy');
INSERT INTO surname_temp (surname) VALUES ('Wheeler');
INSERT INTO surname_temp (surname) VALUES ('Potter');
INSERT INTO surname_temp (surname) VALUES ('Osborne');
INSERT INTO surname_temp (surname) VALUES ('Johnston');
INSERT INTO surname_temp (surname) VALUES ('Gordon');
INSERT INTO surname_temp (surname) VALUES ('Doyle');
INSERT INTO surname_temp (surname) VALUES ('Wallace');
INSERT INTO surname_temp (surname) VALUES ('George');
INSERT INTO surname_temp (surname) VALUES ('Jordan');
INSERT INTO surname_temp (surname) VALUES ('Hutchinson');
INSERT INTO surname_temp (surname) VALUES ('Rowe');
INSERT INTO surname_temp (surname) VALUES ('Burke');
INSERT INTO surname_temp (surname) VALUES ('May');
INSERT INTO surname_temp (surname) VALUES ('Pritchard');
INSERT INTO surname_temp (surname) VALUES ('Gilbert');
INSERT INTO surname_temp (surname) VALUES ('Willis');
INSERT INTO surname_temp (surname) VALUES ('Higgins');
INSERT INTO surname_temp (surname) VALUES ('Read');
INSERT INTO surname_temp (surname) VALUES ('Miles');
INSERT INTO surname_temp (surname) VALUES ('Stevenson');
INSERT INTO surname_temp (surname) VALUES ('Stephenson');
INSERT INTO surname_temp (surname) VALUES ('Hammond');
INSERT INTO surname_temp (surname) VALUES ('Arnold');
INSERT INTO surname_temp (surname) VALUES ('Buckley');
INSERT INTO surname_temp (surname) VALUES ('Walters');
INSERT INTO surname_temp (surname) VALUES ('Hewitt');
INSERT INTO surname_temp (surname) VALUES ('Barber');
INSERT INTO surname_temp (surname) VALUES ('Nelson');
INSERT INTO surname_temp (surname) VALUES ('Slater');
INSERT INTO surname_temp (surname) VALUES ('Austin');
INSERT INTO surname_temp (surname) VALUES ('Sullivan');
INSERT INTO surname_temp (surname) VALUES ('Whitehead');
INSERT INTO surname_temp (surname) VALUES ('Mann');
INSERT INTO surname_temp (surname) VALUES ('Frost');
INSERT INTO surname_temp (surname) VALUES ('Lambert');
INSERT INTO surname_temp (surname) VALUES ('Stephens');
INSERT INTO surname_temp (surname) VALUES ('Blake');
INSERT INTO surname_temp (surname) VALUES ('Akhtar');
INSERT INTO surname_temp (surname) VALUES ('Lynch');
INSERT INTO surname_temp (surname) VALUES ('Goodwin');
INSERT INTO surname_temp (surname) VALUES ('Barton');
INSERT INTO surname_temp (surname) VALUES ('Woodward');
INSERT INTO surname_temp (surname) VALUES ('Thomson');
INSERT INTO surname_temp (surname) VALUES ('Cunningham');
INSERT INTO surname_temp (surname) VALUES ('Quinn');
INSERT INTO surname_temp (surname) VALUES ('Barnett');
INSERT INTO surname_temp (surname) VALUES ('Baxter');
INSERT INTO surname_temp (surname) VALUES ('Bibi');
INSERT INTO surname_temp (surname) VALUES ('Clayton');
INSERT INTO surname_temp (surname) VALUES ('Nash');
INSERT INTO surname_temp (surname) VALUES ('Greenwood');
INSERT INTO surname_temp (surname) VALUES ('Jennings');
INSERT INTO surname_temp (surname) VALUES ('Holt');
INSERT INTO surname_temp (surname) VALUES ('Kemp');
INSERT INTO surname_temp (surname) VALUES ('Poole');
INSERT INTO surname_temp (surname) VALUES ('Gallagher');
INSERT INTO surname_temp (surname) VALUES ('Bond');
INSERT INTO surname_temp (surname) VALUES ('Stokes');
INSERT INTO surname_temp (surname) VALUES ('Tucker');
INSERT INTO surname_temp (surname) VALUES ('Davidson');
INSERT INTO surname_temp (surname) VALUES ('Fowler');
INSERT INTO surname_temp (surname) VALUES ('Heath');
INSERT INTO surname_temp (surname) VALUES ('Norman');
INSERT INTO surname_temp (surname) VALUES ('Middleton');
INSERT INTO surname_temp (surname) VALUES ('Lawson');
INSERT INTO surname_temp (surname) VALUES ('Banks');
INSERT INTO surname_temp (surname) VALUES ('French');
INSERT INTO surname_temp (surname) VALUES ('Stanley');
INSERT INTO surname_temp (surname) VALUES ('Jarvis');
INSERT INTO surname_temp (surname) VALUES ('Gibbs');
INSERT INTO surname_temp (surname) VALUES ('Ferguson');
INSERT INTO surname_temp (surname) VALUES ('Hayward');
INSERT INTO surname_temp (surname) VALUES ('Carroll');
INSERT INTO surname_temp (surname) VALUES ('Douglas');
INSERT INTO surname_temp (surname) VALUES ('Dickinson');
INSERT INTO surname_temp (surname) VALUES ('Todd');
INSERT INTO surname_temp (surname) VALUES ('Barlow');
INSERT INTO surname_temp (surname) VALUES ('Peters');
INSERT INTO surname_temp (surname) VALUES ('Lucas');
INSERT INTO surname_temp (surname) VALUES ('Knowles');
INSERT INTO surname_temp (surname) VALUES ('Hartley');
INSERT INTO surname_temp (surname) VALUES ('Miah');
INSERT INTO surname_temp (surname) VALUES ('Simmons');
INSERT INTO surname_temp (surname) VALUES ('Morton');
INSERT INTO surname_temp (surname) VALUES ('Alexander');
INSERT INTO surname_temp (surname) VALUES ('Field');
INSERT INTO surname_temp (surname) VALUES ('Morrison');
INSERT INTO surname_temp (surname) VALUES ('Norris');
INSERT INTO surname_temp (surname) VALUES ('Townsend');
INSERT INTO surname_temp (surname) VALUES ('Preston');
INSERT INTO surname_temp (surname) VALUES ('Hancock');
INSERT INTO surname_temp (surname) VALUES ('Thornton');
INSERT INTO surname_temp (surname) VALUES ('Baldwin');
INSERT INTO surname_temp (surname) VALUES ('Burrows');
INSERT INTO surname_temp (surname) VALUES ('Briggs');
INSERT INTO surname_temp (surname) VALUES ('Parkinson');
INSERT INTO surname_temp (surname) VALUES ('Reeves');
INSERT INTO surname_temp (surname) VALUES ('MacDonald');
INSERT INTO surname_temp (surname) VALUES ('Lamb');
INSERT INTO surname_temp (surname) VALUES ('Black');
INSERT INTO surname_temp (surname) VALUES ('Abbott');
INSERT INTO surname_temp (surname) VALUES ('Sanders');
INSERT INTO surname_temp (surname) VALUES ('Thorpe');
INSERT INTO surname_temp (surname) VALUES ('Holden');
INSERT INTO surname_temp (surname) VALUES ('Tomlinson');
INSERT INTO surname_temp (surname) VALUES ('Perkins');
INSERT INTO surname_temp (surname) VALUES ('Ashton');
INSERT INTO surname_temp (surname) VALUES ('Rhodes');
INSERT INTO surname_temp (surname) VALUES ('Fuller');
INSERT INTO surname_temp (surname) VALUES ('Howe');
INSERT INTO surname_temp (surname) VALUES ('Bryant');
INSERT INTO surname_temp (surname) VALUES ('Vaughan');
INSERT INTO surname_temp (surname) VALUES ('Dale');
INSERT INTO surname_temp (surname) VALUES ('Davey');
INSERT INTO surname_temp (surname) VALUES ('Weston');
INSERT INTO surname_temp (surname) VALUES ('Bartlett');
INSERT INTO surname_temp (surname) VALUES ('Whittaker');
INSERT INTO surname_temp (surname) VALUES ('Davison');
INSERT INTO surname_temp (surname) VALUES ('Kent');
INSERT INTO surname_temp (surname) VALUES ('Skinner');
INSERT INTO surname_temp (surname) VALUES ('Birch');
INSERT INTO surname_temp (surname) VALUES ('Morley');
INSERT INTO surname_temp (surname) VALUES ('Daniels');
INSERT INTO surname_temp (surname) VALUES ('Glover');
INSERT INTO surname_temp (surname) VALUES ('Howell');
INSERT INTO surname_temp (surname) VALUES ('Cartwright');
INSERT INTO surname_temp (surname) VALUES ('Pugh');
INSERT INTO surname_temp (surname) VALUES ('Humphreys');
INSERT INTO surname_temp (surname) VALUES ('Goddard');
INSERT INTO surname_temp (surname) VALUES ('Brennan');
INSERT INTO surname_temp (surname) VALUES ('Wall');
INSERT INTO surname_temp (surname) VALUES ('Kirby');
INSERT INTO surname_temp (surname) VALUES ('Bowen');
INSERT INTO surname_temp (surname) VALUES ('Savage');
INSERT INTO surname_temp (surname) VALUES ('Bull');
INSERT INTO surname_temp (surname) VALUES ('Wong');
INSERT INTO surname_temp (surname) VALUES ('Dobson');
INSERT INTO surname_temp (surname) VALUES ('Smart');
INSERT INTO surname_temp (surname) VALUES ('Wilkins');
INSERT INTO surname_temp (surname) VALUES ('Kirk');
INSERT INTO surname_temp (surname) VALUES ('Fraser');
INSERT INTO surname_temp (surname) VALUES ('Duffy');
INSERT INTO surname_temp (surname) VALUES ('Hicks');
INSERT INTO surname_temp (surname) VALUES ('Patterson');
INSERT INTO surname_temp (surname) VALUES ('Bradshaw');
INSERT INTO surname_temp (surname) VALUES ('Little');
INSERT INTO surname_temp (surname) VALUES ('Archer');
INSERT INTO surname_temp (surname) VALUES ('Warner');
INSERT INTO surname_temp (surname) VALUES ('Waters');
INSERT INTO surname_temp (surname) VALUES ('O''Sullivan');
INSERT INTO surname_temp (surname) VALUES ('Farrell');
INSERT INTO surname_temp (surname) VALUES ('Brookes');
INSERT INTO surname_temp (surname) VALUES ('Atkins');
INSERT INTO surname_temp (surname) VALUES ('Kay');
INSERT INTO surname_temp (surname) VALUES ('Dodd');
INSERT INTO surname_temp (surname) VALUES ('Bentley');
INSERT INTO surname_temp (surname) VALUES ('Flynn');
INSERT INTO surname_temp (surname) VALUES ('John');
INSERT INTO surname_temp (surname) VALUES ('Schofield');
INSERT INTO surname_temp (surname) VALUES ('Short');
INSERT INTO surname_temp (surname) VALUES ('Haynes');
INSERT INTO surname_temp (surname) VALUES ('Wade');
INSERT INTO surname_temp (surname) VALUES ('Butcher');
INSERT INTO surname_temp (surname) VALUES ('Henry');
INSERT INTO surname_temp (surname) VALUES ('Sanderson');
INSERT INTO surname_temp (surname) VALUES ('Crawford');
INSERT INTO surname_temp (surname) VALUES ('Sheppard');
INSERT INTO surname_temp (surname) VALUES ('Bolton');
INSERT INTO surname_temp (surname) VALUES ('Coates');
INSERT INTO surname_temp (surname) VALUES ('Giles');
INSERT INTO surname_temp (surname) VALUES ('Gould');
INSERT INTO surname_temp (surname) VALUES ('Houghton');
INSERT INTO surname_temp (surname) VALUES ('Gibbons');
INSERT INTO surname_temp (surname) VALUES ('Pratt');
INSERT INTO surname_temp (surname) VALUES ('Manning');
INSERT INTO surname_temp (surname) VALUES ('Law');
INSERT INTO surname_temp (surname) VALUES ('Hooper');
INSERT INTO surname_temp (surname) VALUES ('Noble');
INSERT INTO surname_temp (surname) VALUES ('Dyer');
INSERT INTO surname_temp (surname) VALUES ('Rahman');
INSERT INTO surname_temp (surname) VALUES ('Clements');
INSERT INTO surname_temp (surname) VALUES ('Moran');
INSERT INTO surname_temp (surname) VALUES ('Sykes');
INSERT INTO surname_temp (surname) VALUES ('Chan');
INSERT INTO surname_temp (surname) VALUES ('Doherty');
INSERT INTO surname_temp (surname) VALUES ('Connolly');
INSERT INTO surname_temp (surname) VALUES ('Joyce');
INSERT INTO surname_temp (surname) VALUES ('Franklin');
INSERT INTO surname_temp (surname) VALUES ('Hobbs');
INSERT INTO surname_temp (surname) VALUES ('Coles');
INSERT INTO surname_temp (surname) VALUES ('Herbert');
INSERT INTO surname_temp (surname) VALUES ('Steele');
INSERT INTO surname_temp (surname) VALUES ('Kerr');
INSERT INTO surname_temp (surname) VALUES ('Leach');
INSERT INTO surname_temp (surname) VALUES ('Winter');
INSERT INTO surname_temp (surname) VALUES ('Owens');
INSERT INTO surname_temp (surname) VALUES ('Duncan');
INSERT INTO surname_temp (surname) VALUES ('Naylor');
INSERT INTO surname_temp (surname) VALUES ('Fleming');
INSERT INTO surname_temp (surname) VALUES ('Horton');
INSERT INTO surname_temp (surname) VALUES ('Finch');
INSERT INTO surname_temp (surname) VALUES ('Fitzgerald');
INSERT INTO surname_temp (surname) VALUES ('Randall');
INSERT INTO surname_temp (surname) VALUES ('Carpenter');
INSERT INTO surname_temp (surname) VALUES ('Marsden');
INSERT INTO surname_temp (surname) VALUES ('Browne');
INSERT INTO surname_temp (surname) VALUES ('Garner');
INSERT INTO surname_temp (surname) VALUES ('Pickering');
INSERT INTO surname_temp (surname) VALUES ('Hale');
INSERT INTO surname_temp (surname) VALUES ('Dennis');
INSERT INTO surname_temp (surname) VALUES ('Vincent');
INSERT INTO surname_temp (surname) VALUES ('Chadwick');
INSERT INTO surname_temp (surname) VALUES ('Chandler');
INSERT INTO surname_temp (surname) VALUES ('Sharpe');
INSERT INTO surname_temp (surname) VALUES ('Nolan');
INSERT INTO surname_temp (surname) VALUES ('Lyons');
INSERT INTO surname_temp (surname) VALUES ('Hurst');
INSERT INTO surname_temp (surname) VALUES ('Collier');
INSERT INTO surname_temp (surname) VALUES ('Peacock');
INSERT INTO surname_temp (surname) VALUES ('Howarth');
INSERT INTO surname_temp (surname) VALUES ('Faulkner');
INSERT INTO surname_temp (surname) VALUES ('Rice');
INSERT INTO surname_temp (surname) VALUES ('Pollard');
INSERT INTO surname_temp (surname) VALUES ('Welch');
INSERT INTO surname_temp (surname) VALUES ('Norton');
INSERT INTO surname_temp (surname) VALUES ('Gough');
INSERT INTO surname_temp (surname) VALUES ('Sinclair');
INSERT INTO surname_temp (surname) VALUES ('Blackburn');
INSERT INTO surname_temp (surname) VALUES ('Bryan');
INSERT INTO surname_temp (surname) VALUES ('Conway');
INSERT INTO surname_temp (surname) VALUES ('Power');
INSERT INTO surname_temp (surname) VALUES ('Cameron');
INSERT INTO surname_temp (surname) VALUES ('Daly');
INSERT INTO surname_temp (surname) VALUES ('Allan');
INSERT INTO surname_temp (surname) VALUES ('Hanson');
INSERT INTO surname_temp (surname) VALUES ('Gardiner');
INSERT INTO surname_temp (surname) VALUES ('Boyle');
INSERT INTO surname_temp (surname) VALUES ('Myers');
INSERT INTO surname_temp (surname) VALUES ('Turnbull');
INSERT INTO surname_temp (surname) VALUES ('Wallis');
INSERT INTO surname_temp (surname) VALUES ('Mahmood');
INSERT INTO surname_temp (surname) VALUES ('Sims');
INSERT INTO surname_temp (surname) VALUES ('Swift');
INSERT INTO surname_temp (surname) VALUES ('Iqbal');
INSERT INTO surname_temp (surname) VALUES ('Pope');
INSERT INTO surname_temp (surname) VALUES ('Brady');
INSERT INTO surname_temp (surname) VALUES ('Chamberlain');
INSERT INTO surname_temp (surname) VALUES ('Rowley');
INSERT INTO surname_temp (surname) VALUES ('Tyler');
INSERT INTO surname_temp (surname) VALUES ('Farmer');
INSERT INTO surname_temp (surname) VALUES ('Metcalfe');
INSERT INTO surname_temp (surname) VALUES ('Hilton');
INSERT INTO surname_temp (surname) VALUES ('Godfrey');
INSERT INTO surname_temp (surname) VALUES ('Holloway');
INSERT INTO surname_temp (surname) VALUES ('Parkin');
INSERT INTO surname_temp (surname) VALUES ('Bray');
INSERT INTO surname_temp (surname) VALUES ('Talbot');
INSERT INTO surname_temp (surname) VALUES ('Donnelly');
INSERT INTO surname_temp (surname) VALUES ('Nixon');
INSERT INTO surname_temp (surname) VALUES ('Charlton');
INSERT INTO surname_temp (surname) VALUES ('Benson');
INSERT INTO surname_temp (surname) VALUES ('Whitehouse');
INSERT INTO surname_temp (surname) VALUES ('Barry');
INSERT INTO surname_temp (surname) VALUES ('Hope');
INSERT INTO surname_temp (surname) VALUES ('Lord');
INSERT INTO surname_temp (surname) VALUES ('North');
INSERT INTO surname_temp (surname) VALUES ('Storey');
INSERT INTO surname_temp (surname) VALUES ('Connor');
INSERT INTO surname_temp (surname) VALUES ('Potts');
INSERT INTO surname_temp (surname) VALUES ('Bevan');
INSERT INTO surname_temp (surname) VALUES ('Hargreaves');
INSERT INTO surname_temp (surname) VALUES ('McLean');
INSERT INTO surname_temp (surname) VALUES ('Mistry');
INSERT INTO surname_temp (surname) VALUES ('Bruce');
INSERT INTO surname_temp (surname) VALUES ('Howells');
INSERT INTO surname_temp (surname) VALUES ('Hyde');
INSERT INTO surname_temp (surname) VALUES ('Parkes');
INSERT INTO surname_temp (surname) VALUES ('Wyatt');
INSERT INTO surname_temp (surname) VALUES ('Fry');
INSERT INTO surname_temp (surname) VALUES ('Lees');
INSERT INTO surname_temp (surname) VALUES ('O''Donnell');
INSERT INTO surname_temp (surname) VALUES ('Craig');
INSERT INTO surname_temp (surname) VALUES ('Forster');
INSERT INTO surname_temp (surname) VALUES ('McKenzie');
INSERT INTO surname_temp (surname) VALUES ('Humphries');
INSERT INTO surname_temp (surname) VALUES ('Mellor');
INSERT INTO surname_temp (surname) VALUES ('Carey');
INSERT INTO surname_temp (surname) VALUES ('Ingram');
INSERT INTO surname_temp (surname) VALUES ('Summers');
INSERT INTO surname_temp (surname) VALUES ('Leonard');

DROP TABLE IF EXISTS fornames_temp;

CREATE TEMP TABLE fornames_temp
(
	id			serial,
	forename	varchar(255),
	sex			varchar(1),
	title		int
);

-- Boys names most popular for 2007 taken from http://www.statistics.gov.uk/specials/babiesnames_boys.asp
-- Girls names most popular for 2007 taken from http://www.statistics.gov.uk/specials/babiesnames_girls.asp

INSERT INTO fornames_temp (forename, sex, title) VALUES ('JACK', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('THOMAS', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('OLIVER', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('JOSHUA', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('HARRY', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('CHARLIE', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('DANIEL', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('WILLIAM', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('JAMES', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('ALFIE', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('SAMUEL', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('GEORGE', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('JOSEPH', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('BENJAMIN', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('ETHAN', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('LEWIS', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('MOHAMMED', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('JAKE', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('DYLAN', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('JACOB', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('LUKE', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('CALLUM', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('ALEXANDER', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('MATTHEW', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('RYAN', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('ADAM', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('TYLER', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('LIAM', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('HARVEY', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('MAX', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('HARRISON', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('JAYDEN', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('CAMERON', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('HENRY', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('ARCHIE', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('CONNOR', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('JAMIE', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('MUHAMMAD', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('OSCAR', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('EDWARD', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('LUCAS', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('ISAAC', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('LEO', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('OWEN', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('NATHAN', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('MICHAEL', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('FINLEY', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('BEN', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('AARON', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('NOAH', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('TOBY', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('CHARLES', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('KYLE', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('LOGAN', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('MASON', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('RHYS', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('ALEX', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('RILEY', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('FINLAY', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('LOUIS', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('KIERAN', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('KAI', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('FREDDIE', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('DAVID', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('REECE', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('BRANDON', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('BRADLEY', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('KIAN', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('HARLEY', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('BAILEY', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('MOHAMMAD', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('LUCA', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('THEO', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('JOHN', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('LEON', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('ASHTON', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('SAM', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('ELLIS', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('AIDAN', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('JOEL', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('HAYDEN', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('EVAN', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('ZACHARY', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('ROBERT', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('JOE', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('SEBASTIAN', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('BILLY', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('TAYLOR', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('ELLIOT', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('CHRISTOPHER', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('REUBEN', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('GABRIEL', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('MORGAN', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('COREY', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('LOUIE', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('JAY', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('DOMINIC', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('SEAN', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('ANDREW', 'M', cast(random() * 4 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('ZAK', 'M', cast(random() * 4 + 1 as int));

INSERT INTO fornames_temp (forename, sex, title) VALUES ('GRACE', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('RUBY', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('OLIVIA', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('EMILY', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('JESSICA', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('SOPHIE', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('CHLOE', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('LILY', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('ELLA', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('AMELIA', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('LUCY', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('CHARLOTTE', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('ELLIE', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('MIA', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('EVIE', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('HANNAH', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('MEGAN', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('KATIE', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('ISABELLA', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('ISABELLE', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('MILLIE', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('ABIGAIL', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('AMY', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('DAISY', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('FREYA', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('EMMA', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('ERIN', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('POPPY', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('MOLLY', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('HOLLY', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('PHOEBE', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('JASMINE', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('CAITLIN', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('IMOGEN', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('MADISON', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('ELIZABETH', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('SOPHIA', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('KEIRA', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('SCARLETT', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('LEAH', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('AVA', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('GEORGIA', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('ALICE', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('SUMMER', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('ISABEL', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('REBECCA', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('LAUREN', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('AMBER', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('ELEANOR', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('BETHANY', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('LOLA', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('EVA', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('PAIGE', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('BROOKE', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('LILLY', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('LIBBY', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('ISOBEL', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('ANNA', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('AMELIE', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('MAISIE', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('ROSIE', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('MATILDA', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('MADDISON', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('SIENNA', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('SARAH', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('NIAMH', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('SKYE', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('GRACIE', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('ZARA', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('ISLA', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('TIA', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('ALISHA', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('HARRIET', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('FAITH', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('AIMEE', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('EVE', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('SOFIA', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('ZOE', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('MAYA', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('MADELEINE', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('COURTNEY', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('LACEY', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('NICOLE', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('LAYLA', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('LYDIA', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('ABBIE', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('MARTHA', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('FRANCESCA', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('JULIA', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('SHANNON', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('LEXIE', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('HOLLIE', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('MARIA', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('ALEXANDRA', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('ROSE', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('ALICIA', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('VICTORIA', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('SARA', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('EVELYN', 'F', cast(random() * 6 + 1 as int));
INSERT INTO fornames_temp (forename, sex, title) VALUES ('TILLY', 'F', cast(random() * 6 + 1 as int));

UPDATE fornames_temp
SET forename = CONCAT(LEFT(forename, 1), LOWER(SUBSTRING(forename, 2, 100)));

CREATE TEMP TABLE title_m_temp
(
	id			serial,
	title		varchar(255)
);


INSERT INTO title_m_temp (title) VALUES ('Mr');
INSERT INTO title_m_temp (title) VALUES ('Dr');
INSERT INTO title_m_temp (title) VALUES ('Rev');
INSERT INTO title_m_temp (title) VALUES ('Prof');

CREATE TEMP TABLE title_f_temp
(
	id			serial,
	title		varchar(255)
);

INSERT INTO title_f_temp (title) VALUES ('Ms');
INSERT INTO title_f_temp (title) VALUES ('Miss');
INSERT INTO title_f_temp (title) VALUES ('Mrs');
INSERT INTO title_f_temp (title) VALUES ('Dr');
INSERT INTO title_f_temp (title) VALUES ('Rev');
INSERT INTO title_f_temp (title) VALUES ('Prof');

insert into reporting.customer
(surname,initials,firstname,title,postcode1,postcode2,dob,sex,email,passwd)
select --top (@TotalCustomersPerSex)
s.surname, 
upper(substring(f.forename, 3,1)) as Initials, 
f.forename, 
tf.title,
concat('PE', cast(1 + ROW_NUMBER() over (order by s.surname) % 99 as varchar)) as PostCode1,
concat(cast(1 + ROW_NUMBER() over (order by tf.id) % 9 as varchar), upper(substring(f.forename, 2,2))) as PostCode2,
date '1900-01-01' + ASCII(SUBSTRING(f.forename,1,1)) * interval '1 day' + ASCII(SUBSTRING(f.forename,1,1)) * interval '12 months',
f.sex,
lower(concat(f.forename, '.', s.surname, '@', s.surname, '.me.uk')) as Email,
concat(upper(substring(REVERSE(f.forename),1,4)), substring(REVERSE(s.surname),1,4)) as Passwd
from fornames_temp f
inner join title_f_temp tf on f.sex = 'F' and tf.id = f.title
cross join surname_temp s
order by s.surname limit :customer_gender_limit;

insert into reporting.customer
(surname,initials,firstname,title,postcode1,postcode2,dob,sex,email,passwd)
select --top (@TotalCustomersPerSex)
s.surname, 
upper(substring(f.forename, 3,1)) as Initials, 
f.forename, 
tm.title,
concat('PE', cast(1 + ROW_NUMBER() over (order by s.surname) % 99 as varchar)) as PostCode1,
concat(cast(1 + ROW_NUMBER() over (order by tm.id) % 9 as varchar), upper(substring(f.forename, 2,2))) as PostCode2,
date '1900-01-01' + ASCII(SUBSTRING(f.forename,1,1)) * interval '1 day' + ASCII(SUBSTRING(f.forename,1,1)) * interval '12 months',
f.sex,
lower(concat(f.forename, '.', s.surname, '@', s.surname, '.me.uk')) as Email,
concat(upper(substring(REVERSE(f.forename),1,4)), substring(REVERSE(s.surname),1,4)) as Passwd
from fornames_temp f
inner join title_m_temp tm on f.sex = 'M' and tm.id = f.title
cross join surname_temp s
order by s.surname limit :customer_gender_limit;



